import type { Metadata } from "next";

import "./globals.css";
import "./fonts.css";

export const metadata: Metadata = {
  title: "Lindway",
  description: "Generated by Lindway",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`flex flex-col min-h-screen overflow-x-hidden`}>{children}</body>
    </html>
  );
}
