import type { Metadata } from "next";

import { Poppins } from "next/font/google";

import "./globals.css";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Lindway",
  description: "Generated by Lindway",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} flex flex-col min-h-screen overflow-x-hidden`}>{children}</body>
    </html>
  );
}
